sudo: false

language: php

dist: trusty

php:
    - 7.1
    - 7.3

env:
    global:
        - TMPDIR=/tmp
    matrix:
        - WP_VERSION=4.9.8 WP_MULTISITE=0 PREFER_LOWEST=""
        - WP_VERSION=4.9.8 WP_MULTISITE=1 PREFER_LOWEST=""
        - WP_VERSION=latest WP_MULTISITE=0 PREFER_LOWEST=""
        - WP_VERSION=latest WP_MULTISITE=1 PREFER_LOWEST=""

matrix:
    exclude:
    - php: 7.3
      env: WP_VERSION=4.9.8 WP_MULTISITE=0 PREFER_LOWEST=""
    - php: 7.3
      env: WP_VERSION=4.9.8 WP_MULTISITE=1 PREFER_LOWEST=""

before_script:
    - if [ "$TRAVIS_PHP_VERSION" == 7.1 ]; then pear config-set preferred_state beta; pecl channel-update pecl.php.net; yes | pecl install imagick; fi
    - bash bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION
    # composer install --dev --prefer-source
    - composer update $PREFER_LOWEST --dev --prefer-source
    - composer require satooshi/php-coveralls:1.0.*

script:
    - if [ "$TRAVIS_BRANCH" == "master" ] || [ "$TRAVIS_BRANCH" == "2.x" ] && [ "$TRAVIS_PHP_VERSION" == 7.1 ]; then mkdir -p build/logs; vendor/phpunit/phpunit/phpunit --coverage-clover build/logs/clover.xml -c phpunit.xml; else vendor/phpunit/phpunit/phpunit -c phpunit-nocover.xml; fi

after_script:
    - if [ "$TRAVIS_BRANCH" == "master" ] || [ "$TRAVIS_BRANCH" == "2.x" ] && [ "$TRAVIS_PHP_VERSION" == 7.1 ]; then php vendor/bin/coveralls -v; fi

after_success:
    - if [ "$TRAVIS_BRANCH" == "master" ] || [ "$TRAVIS_BRANCH" == "2.x" ] && [ "$TRAVIS_PHP_VERSION" == 7.1 ]; then coveralls; fi
    - bash <(curl -s https://codecov.io/bash)
