sudo: false

language: php

php:
    - 5.4
    - 5.5
    - 7.0

env:
    - WP_VERSION=latest WP_MULTISITE=0
    - WP_VERSION=latest WP_MULTISITE=1

matrix:
    include:
        - php: 5.3
          env: WP_VERSION=latest WP_MULTISITE=0
        - php: hhvm
          env: WP_VERSION=latest WP_MULTISITE=1

before_script:
    - if [ "$TRAVIS_PHP_VERSION" -ge "5.4" ]; then autodetect | pecl install imagick; fi
    - if [ "$TRAVIS_PHP_VERSION" == 5.3 ]; then autodetect | pecl install imagick-3.0.1; fi
    - bash bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION
    - composer install --dev --prefer-source

script:
    - if [ "$TRAVIS_BRANCH" == "master" ]; then mkdir -p build/logs; phpunit --coverage-clover build/logs/clover.xml; fi
    - if [ "$TRAVIS_BRANCH" != "master" ]; then phpunit -c bin/phpunit-nocover.xml; fi

after_script:
    - if [ "$TRAVIS_BRANCH" == "master" ]; then php vendor/bin/coveralls -v; fi

after_success:
    - if [ "$TRAVIS_BRANCH" == "master" ]; then coveralls; fi
