language: php

php:
    - 5.2.17
    - 5.3
    - 5.4

env:
    - WP_VERSION=3.9 WP_MULTISITE=0
    - WP_VERSION=3.9 WP_MULTISITE=1
    - WP_VERSION=3.8.3 WP_MULTISITE=0
    - WP_VERSION=3.8.3 WP_MULTISITE=1
    - WP_VERSION=3.7.3 WP_MULTISITE=0
    - WP_VERSION=3.7.3 WP_MULTISITE=1

before_script:
    - bash bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION

script: phpunit
